[32mINFO    [0m pytest_operator.plugin:plugin.py:834 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.8    unsupported  01:45:07Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
postgresql                14.11    active      3  postgresql                                 0  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable   72  no       

Unit                         Workload  Agent  Machine  Public address  Ports     Message
postgresql/0                 active    idle   0        10.79.46.218    5432/tcp  Primary
postgresql/1                 active    idle   1        10.79.46.37     5432/tcp  
postgresql/2*                active    idle   2        10.79.46.44     5432/tcp  
self-signed-certificates/0*  active    idle   3        10.79.46.179              

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.79.46.218  juju-b3ab9e-0  ubuntu@22.04      Running
1        started  10.79.46.37   juju-b3ab9e-1  ubuntu@22.04      Running
2        started  10.79.46.44   juju-b3ab9e-2  ubuntu@22.04      Running
3        started  10.79.46.179  juju-b3ab9e-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:840 Juju error logs:

machine-2: 01:31:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:31:42 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:31:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:31:42 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 01:31:42 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:31:42 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:31:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-self-signed-certificates-0: 01:31:43 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-0: 01:31:45 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:31:45 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:31:45 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:31:45 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:31:46 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:31:46 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:31:46 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:31:47 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-2: 01:35:10 ERROR unit.postgresql/2.juju-log certificates:3: Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/./src/charm.py", line 1432, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop_after_delay=stop_after_delay(300)):
TypeError: BaseRetrying.__init__() got an unexpected keyword argument 'stop_after_delay'
unit-postgresql-2: 01:42:42 ERROR unit.postgresql/2.juju-log Non-existing secret cauth was attempted to be removed.
unit-postgresql-2: 01:42:42 ERROR unit.postgresql/2.juju-log Non-existing secret cert was attempted to be removed.
unit-postgresql-2: 01:42:42 ERROR unit.postgresql/2.juju-log Non-existing secret chain was attempted to be removed.
unit-self-signed-certificates-0: 01:42:43 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "8a75648c-38c9-4628-891b-3a0908b3ab9e:r#3#postgresql": settings 8a75648c-38c9-4628-891b-3a0908b3ab9e:r#3#postgresql not found (not found)
unit-postgresql-2: 01:42:56 ERROR unit.postgresql/2.juju-log Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-2/charm/./src/charm.py", line 1432, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop_after_delay=stop_after_delay(300)):
TypeError: BaseRetrying.__init__() got an unexpected keyword argument 'stop_after_delay'
unit-postgresql-0: 01:43:04 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "8a75648c-38c9-4628-891b-3a0908b3ab9e:r#3#self-signed-certificates": settings 8a75648c-38c9-4628-891b-3a0908b3ab9e:r#3#self-signed-certificates not found (not found)
unit-postgresql-2: 01:43:10 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "8a75648c-38c9-4628-891b-3a0908b3ab9e:r#3#self-signed-certificates": settings 8a75648c-38c9-4628-891b-3a0908b3ab9e:r#3#self-signed-certificates not found (not found)
unit-postgresql-1: 01:43:24 ERROR unit.postgresql/1.juju-log restart:1: Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-1/charm/./src/charm.py", line 1432, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop_after_delay=stop_after_delay(300)):
TypeError: BaseRetrying.__init__() got an unexpected keyword argument 'stop_after_delay'
unit-postgresql-0: 01:44:29 ERROR unit.postgresql/0.juju-log restart:1: Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-0/charm/./src/charm.py", line 1432, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop_after_delay=stop_after_delay(300)):
TypeError: BaseRetrying.__init__() got an unexpected keyword argument 'stop_after_delay'

[32mINFO    [0m pytest_operator.plugin:plugin.py:904 Forgetting main...