[32mINFO    [0m integration.test_backups:test_backups.py:316 configuring S3 integrator for an invalid cloud
[32mINFO    [0m integration.test_backups:test_backups.py:331 waiting for the database charm to become blocked
[32mINFO    [0m integration.test_backups:test_backups.py:338 configuring S3 integrator for a valid cloud, but with the path of another cluster repository
[32mINFO    [0m integration.test_backups:test_backups.py:347 waiting for the database charm to become blocked
[32mINFO    [0m integration.test_backups:test_backups.py:354 configuring S3 integrator for a valid cloud
[32mINFO    [0m integration.test_backups:test_backups.py:358 waiting for the database charm to become active
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  new-postgresql/0 [executing] blocked: the S3 repository has backups from another cluster
  s3-integrator/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  new-postgresql/0 [executing] maintenance: initialising stanza
[32mINFO    [0m juju.model:model.py:2971 Waiting for model:
  new-postgresql/0 [idle] active: Primary
[32mINFO    [0m integration.test_backups:test_backups.py:84 deleting the previously created backups
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.8    unsupported  02:17:38Z

App             Version  Status  Scale  Charm          Channel        Rev  Exposed  Message
new-postgresql  14.11    active      1  postgresql                      1  no       
s3-integrator            active      1  s3-integrator  latest/stable   24  no       

Unit               Workload  Agent  Machine  Public address  Ports     Message
new-postgresql/0*  active    idle   5        10.233.130.66   5432/tcp  Primary
s3-integrator/0*   active    idle   0        10.233.130.244            

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.233.130.244  juju-983f17-0  ubuntu@22.04      Running
5        started  10.233.130.66   juju-983f17-5  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:49:28 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:49:28 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:49:28 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-s3-integrator-0: 01:49:28 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:49:32 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:49:32 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:49:32 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:49:32 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:49:55 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:49:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:49:55 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-gcp-1: 01:49:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:49:57 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:49:57 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:49:57 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-gcp-0: 01:49:57 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 02:02:49 ERROR juju.api.watcher error trying to stop watcher: websocket: close sent
machine-3: 02:08:50 ERROR juju.api.watcher error trying to stop watcher: websocket: close sent
machine-4: 02:09:58 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-4: 02:09:58 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 02:09:58 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-gcp-2: 02:09:58 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 02:10:11 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 02:10:11 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 02:10:11 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-new-postgresql-0: 02:10:11 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-new-postgresql-0: 02:11:06 ERROR unit.new-postgresql/0.juju-log Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

machine-4: 02:12:15 ERROR juju.api.watcher error trying to stop watcher: websocket: close sent
unit-new-postgresql-0: 02:15:55 ERROR unit.new-postgresql/0.juju-log s3-parameters:13: Failed to create a session 'bucket' in region=region.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/src/backups.py", line 268, in _create_bucket_if_not_exists
    s3 = session.resource(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/session.py", line 444, in resource
    client = self.client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/session.py", line 297, in client
    return self._session.create_client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 520, in _get_client_args
    return args_creator.get_client_args(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/args.py", line 137, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: endpoint
unit-new-postgresql-0: 02:15:57 ERROR unit.new-postgresql/0.juju-log s3-parameters:13: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/./src/charm.py", line 1840, in <module>
    main(PostgresqlOperatorCharm)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/main.py", line 548, in main
    manager.run()
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/main.py", line 527, in run
    self._emit()
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/main.py", line 516, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/lib/charms/data_platform_libs/v0/s3.py", line 768, in _on_relation_changed
    getattr(self.on, "credentials_changed").emit(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/src/backups.py", line 604, in _on_s3_credential_changed
    self._create_bucket_if_not_exists()
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 647, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/src/backups.py", line 294, in _create_bucket_if_not_exists
    bucket.create(CreateBucketConfiguration={"LocationConstraint": region})
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/resources/factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 974, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 1048, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/validate.py", line 381, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter CreateBucketConfiguration.LocationConstraint, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
unit-new-postgresql-0: 02:15:57 ERROR juju.worker.uniter.operation hook "s3-parameters-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...