{"uid":"6c2bdb2657c0c1af","name":"test_freeze_db_process[postgres]","fullName":"tests.integration.ha_tests.test_self_healing#test_freeze_db_process","historyId":"0407c40b818b0635f05a8c1e450fc7bb","time":{"start":1708740757288,"stop":1708741118032,"duration":360744},"status":"failed","statusMessage":"AssertionError: secondary not up to date with the cluster after restarting.","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 493, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 115, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 152, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 114, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 493, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 115, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 152, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 114, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 532, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/test_self_healing.py\", line 208, in test_freeze_db_process\n    await is_cluster_updated(ops_test, primary_name)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/helpers.py\", line 202, in is_cluster_updated\n    assert await is_secondary_up_to_date(\nAssertionError: secondary not up to date with the cluster after restarting.","flaky":true,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop","time":{"start":1708738062122,"stop":1708738062122,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1708738062122,"stop":1708738062122,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1708738062122,"stop":1708738062396,"duration":274},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"primary_start_timeout","time":{"start":1708740602901,"stop":1708740607255,"duration":4354},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1708740757287,"stop":1708740757287,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"continuous_writes","time":{"start":1708740757288,"stop":1708740757288,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: secondary not up to date with the cluster after restarting.","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: Optional[TResult] = func()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 262, in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 493, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 115, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 152, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 114, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 177, in pytest_runtest_call\n    raise e\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 169, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1792, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 493, in __call__\n    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 115, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 152, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 114, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 194, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 532, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/test_self_healing.py\", line 208, in test_freeze_db_process\n    await is_cluster_updated(ops_test, primary_name)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/helpers.py\", line 202, in is_cluster_updated\n    assert await is_secondary_up_to_date(\nAssertionError: secondary not up to date with the cluster after restarting.","steps":[],"attachments":[{"uid":"630f1af63bc7eee","name":"log","source":"630f1af63bc7eee.txt","type":"text/plain","size":509}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"continuous_writes::finalizer","time":{"start":1708741118067,"stop":1708741119149,"duration":1082},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail::0","time":{"start":1708741119152,"stop":1708741119152,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"primary_start_timeout::finalizer","time":{"start":1708742775083,"stop":1708742908830,"duration":133747},"status":"broken","statusMessage":"tenacity.RetryError: RetryError[<Future at 0x7f64e5e63220 state=finished raised ConnectTimeout>]\n","statusTrace":"  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 302, in finalizer\n    event_loop.run_until_complete(async_finalizer())\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 294, in async_finalizer\n    await gen_obj.__anext__()\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/conftest.py\", line 58, in primary_start_timeout\n    await change_patroni_setting(\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/tests/integration/ha_tests/helpers.py\", line 129, in change_patroni_setting\n    for attempt in Retrying(stop=stop_after_delay(30 * 2), wait=wait_fixed(3)):\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 347, in __iter__\n    do = self.iter(retry_state=retry_state)\n  File \"/home/ubuntu/github-runner/_work/postgresql-operator/postgresql-operator/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py\", line 326, in iter\n    raise retry_exc from fut.exception()\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1708742908839,"stop":1708742909503,"duration":664},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1708742909507,"stop":1708742909507,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1708742909507,"stop":1708742909508,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1708742909508,"stop":1708742909508,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration.ha_tests"},{"name":"suite","value":"test_self_healing"},{"name":"host","value":"large-307-0401c843e9bc1acf49cf70fb"},{"name":"thread","value":"14135-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.ha_tests.test_self_healing"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"process","value":"'postgres'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":21,"unknown":0,"total":24},"items":[{"uid":"fdb3beb047fc86eb","reportUrl":"../2055//#testresult/fdb3beb047fc86eb","status":"passed","time":{"start":1708654078943,"stop":1708654261683,"duration":182740}},{"uid":"632af0aa2d13016","reportUrl":"../2032//#testresult/632af0aa2d13016","status":"passed","time":{"start":1708481276440,"stop":1708481439506,"duration":163066}},{"uid":"999ef2a0494c2557","reportUrl":"../2027//#testresult/999ef2a0494c2557","status":"passed","time":{"start":1708394793987,"stop":1708394947269,"duration":153282}},{"uid":"f98c615b781a0a7f","reportUrl":"../2025//#testresult/f98c615b781a0a7f","status":"failed","statusDetails":"AssertionError: members report different lists of cluster members.","time":{"start":1708308895678,"stop":1708309048936,"duration":153258}},{"uid":"389e025a485c5ec1","reportUrl":"../2019//#testresult/389e025a485c5ec1","status":"passed","time":{"start":1708135534454,"stop":1708135720781,"duration":186327}},{"uid":"771ab20cdb57ca06","reportUrl":"../2013//#testresult/771ab20cdb57ca06","status":"passed","time":{"start":1708049394268,"stop":1708049568514,"duration":174246}},{"uid":"bf49dfde01d6b6ed","reportUrl":"../2008//#testresult/bf49dfde01d6b6ed","status":"passed","time":{"start":1707963272619,"stop":1707963398001,"duration":125382}},{"uid":"b580cd79cb661ef","reportUrl":"../2000//#testresult/b580cd79cb661ef","status":"passed","time":{"start":1707789624638,"stop":1707789793757,"duration":169119}},{"uid":"3084230c5cdae083","reportUrl":"../1996//#testresult/3084230c5cdae083","status":"failed","statusDetails":"AssertionError: secondary not up to date with the cluster after restarting.","time":{"start":1707703797806,"stop":1707704107837,"duration":310031}},{"uid":"f3a66d478440e04f","reportUrl":"../1995//#testresult/f3a66d478440e04f","status":"passed","time":{"start":1707617272723,"stop":1707617430656,"duration":157933}},{"uid":"29c6d09f4e3b885a","reportUrl":"../1990//#testresult/29c6d09f4e3b885a","status":"passed","time":{"start":1707444702527,"stop":1707444882548,"duration":180021}},{"uid":"484d6bf24bab54e2","reportUrl":"../1988//#testresult/484d6bf24bab54e2","status":"passed","time":{"start":1707357838536,"stop":1707357995216,"duration":156680}},{"uid":"fd4385d70549cec8","reportUrl":"../1973//#testresult/fd4385d70549cec8","status":"passed","time":{"start":1707271333874,"stop":1707271434998,"duration":101124}},{"uid":"ceaf850c9b9f8d73","reportUrl":"../1961//#testresult/ceaf850c9b9f8d73","status":"passed","time":{"start":1707184698530,"stop":1707184872778,"duration":174248}},{"uid":"411ad357d176a5d4","reportUrl":"../1957//#testresult/411ad357d176a5d4","status":"passed","time":{"start":1707099033060,"stop":1707099151441,"duration":118381}},{"uid":"1b2207bee4d5018","reportUrl":"../1956//#testresult/1b2207bee4d5018","status":"passed","time":{"start":1707011824150,"stop":1707011991545,"duration":167395}},{"uid":"4c65da34274c5967","reportUrl":"../1955//#testresult/4c65da34274c5967","status":"passed","time":{"start":1706925875924,"stop":1706926043276,"duration":167352}},{"uid":"15f8bbd81ed41a18","reportUrl":"../1939//#testresult/15f8bbd81ed41a18","status":"passed","time":{"start":1706753752341,"stop":1706753873850,"duration":121509}},{"uid":"ad62e39833cccf52","reportUrl":"../1935//#testresult/ad62e39833cccf52","status":"passed","time":{"start":1706671166492,"stop":1706671283194,"duration":116702}},{"uid":"1d97821b780f19e2","reportUrl":"../1928//#testresult/1d97821b780f19e2","status":"passed","time":{"start":1706580158749,"stop":1706580332704,"duration":173955}}]},"tags":["asyncio","group(1)"]},"source":"6c2bdb2657c0c1af.json","parameterValues":["'postgres'"]}