[32mINFO    [0m integration.test_backups:test_backups.py:77 deleting the previously created backups
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.8    unsupported  02:23:36Z

App                       Version  Status  Scale  Charm                     Channel        Rev  Exposed  Message
postgresql-gcp            14.11    active      2  postgresql                                 1  no       
s3-integrator                      active      1  s3-integrator             latest/stable   17  no       
self-signed-certificates           active      1  self-signed-certificates  latest/stable   72  no       

Unit                         Workload     Agent      Machine  Public address  Ports     Message
postgresql-gcp/0*            maintenance  executing  5        10.4.104.213    5432/tcp  checking stanza
postgresql-gcp/1             waiting      idle       6        10.4.104.200    5432/tcp  awaiting for cluster to start
s3-integrator/0*             active       idle       0        10.4.104.171              
self-signed-certificates/0*  active       idle       1        10.4.104.25               

Machine  State    Address       Inst id        Base          AZ  Message
0        started  10.4.104.171  juju-6e196b-0  ubuntu@22.04      Running
1        started  10.4.104.25   juju-6e196b-1  ubuntu@22.04      Running
5        started  10.4.104.213  juju-6e196b-5  ubuntu@22.04      Running
6        started  10.4.104.200  juju-6e196b-6  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:31:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:31:29 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:31:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:31:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:31:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:31:29 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-s3-integrator-0: 01:31:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-self-signed-certificates-0: 01:31:29 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:31:45 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:31:45 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:31:45 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-aws-1: 01:31:45 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:32:08 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:32:08 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:32:08 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-aws-0: 01:32:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-aws-1: 01:41:01 ERROR unit.postgresql-aws/1.juju-log certificates:5: Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-aws-1/charm/./src/charm.py", line 1471, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop_after_delay=stop_after_delay(300)):
TypeError: BaseRetrying.__init__() got an unexpected keyword argument 'stop_after_delay'
unit-postgresql-aws-1: 01:51:19 ERROR unit.postgresql-aws/1.juju-log certificates:5: Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-aws-1/charm/./src/charm.py", line 1471, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop_after_delay=stop_after_delay(300)):
TypeError: BaseRetrying.__init__() got an unexpected keyword argument 'stop_after_delay'
machine-4: 01:52:47 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-4: 01:52:47 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:52:47 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-aws-2: 01:52:48 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-5: 01:59:10 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-5: 01:59:10 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 01:59:10 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:59:10 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-6: 01:59:10 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 01:59:10 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-gcp-0: 01:59:10 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-gcp-1: 01:59:11 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-gcp-0: 02:07:05 ERROR unit.postgresql-gcp/0.juju-log s3-parameters:9: Failed to list PostgreSQL database users: could not translate host name "None" to address: Temporary failure in name resolution

unit-postgresql-gcp-0: 02:08:30 ERROR unit.postgresql-gcp/0.juju-log certificates:10: Unable to reconnect to postgresql
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-gcp-0/charm/./src/charm.py", line 1471, in _restart
    for attempt in Retrying(wait=wait_fixed(3), stop_after_delay=stop_after_delay(300)):
TypeError: BaseRetrying.__init__() got an unexpected keyword argument 'stop_after_delay'
unit-postgresql-gcp-0: 02:21:07 ERROR unit.postgresql-gcp/0.juju-log database-peers:7: RetryError[<Future at 0x7f41e4566830 state=finished raised Exception>]
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-gcp-0/charm/src/backups.py", line 447, in check_stanza
    raise Exception(stderr)
Exception: WARN: unable to check pg2: [HostConnectError] unable to connect to '10.4.104.200:8432': [111] Connection refused
          [HostConnectError] on 12 retries from 100-60000ms: unable to connect to '10.4.104.200:8432': [111] Connection refused
ERROR: [049]: unable to connect to '10.4.104.200:8432': [111] Connection refused
           [HostConnectError] on 12 retries from 100-60000ms: unable to connect to '10.4.104.200:8432': [111] Connection refused


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-gcp-0/charm/src/backups.py", line 436, in check_stanza
    for attempt in Retrying(stop=stop_after_attempt(5), wait=wait_fixed(3)):
  File "/var/lib/juju/agents/unit-postgresql-gcp-0/charm/venv/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-postgresql-gcp-0/charm/venv/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f41e4566830 state=finished raised Exception>]

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...