[32mINFO    [0m integration.test_backups:test_backups.py:330 configuring S3 integrator for an invalid cloud
[32mINFO    [0m integration.test_backups:test_backups.py:347 waiting for the database charm to become blocked
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  new-postgresql/0 [executing] blocked: failed to access/create the bucket, check your S3 settings
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  s3-integrator/0 [idle] active: 
[32mINFO    [0m integration.test_backups:test_backups.py:357 configuring S3 integrator for a valid cloud, but with the path of another cluster repository
[32mINFO    [0m integration.test_backups:test_backups.py:366 waiting for the database charm to become blocked
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  s3-integrator/0 [idle] active: 
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  new-postgresql/0 [executing] blocked: failed to access/create the bucket, check your S3 settings
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  new-postgresql/0 [idle] blocked: the S3 repository has backups from another cluster
[32mINFO    [0m integration.test_backups:test_backups.py:376 configuring S3 integrator for a valid cloud
[32mINFO    [0m integration.test_backups:test_backups.py:380 waiting for the database charm to become active
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  new-postgresql/0 [idle] blocked: the S3 repository has backups from another cluster
  s3-integrator/0 [executing] active: 
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  new-postgresql/0 [executing] maintenance: initialising stanza
[32mINFO    [0m juju.model:model.py:2947 Waiting for model:
  new-postgresql/0 [idle] active:
[32mINFO    [0m pytest_operator.plugin:plugin.py:784 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.7    unsupported  04:28:13Z

App             Version  Status  Scale  Charm          Channel        Rev  Exposed  Message
new-postgresql  14.10    active      1  postgresql                      2  no       Primary
s3-integrator            active      1  s3-integrator  latest/stable   13  no       

Unit               Workload  Agent  Machine  Public address  Ports     Message
new-postgresql/0*  active    idle   7        10.187.227.68   5432/tcp  Primary
s3-integrator/0*   active    idle   0        10.187.227.238            

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.187.227.238  juju-47f61f-0  ubuntu@22.04      Running
7        started  10.187.227.68   juju-47f61f-7  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:790 Juju error logs:

machine-0: 03:04:38 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 03:04:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 03:04:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-s3-integrator-0: 03:04:38 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 03:04:41 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 03:04:41 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 03:04:41 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-tls-certificates-operator-0: 03:04:42 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 03:04:57 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 03:04:57 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 03:04:57 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-aws-1: 03:04:58 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 03:05:07 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 03:05:07 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 03:05:07 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-aws-0: 03:05:08 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-aws-0: 03:18:44 ERROR unit.postgresql-aws/0.juju-log certificates:6: Non-existing secret {'cauth'} was attempted to be removed.
unit-postgresql-aws-0: 03:18:44 ERROR unit.postgresql-aws/0.juju-log certificates:6: Can't update secret for relation 4
unit-postgresql-aws-0: 03:18:44 ERROR unit.postgresql-aws/0.juju-log certificates:6: Non-existing field 'cauth' was attempted to be removed from the databag (relation ID: 4)
unit-postgresql-aws-0: 03:18:45 ERROR unit.postgresql-aws/0.juju-log certificates:6: Non-existing secret {'cert'} was attempted to be removed.
unit-postgresql-aws-0: 03:18:45 ERROR unit.postgresql-aws/0.juju-log certificates:6: Can't update secret for relation 4
unit-postgresql-aws-0: 03:18:45 ERROR unit.postgresql-aws/0.juju-log certificates:6: Non-existing field 'cert' was attempted to be removed from the databag (relation ID: 4)
unit-postgresql-aws-0: 03:18:45 ERROR unit.postgresql-aws/0.juju-log certificates:6: Non-existing secret {'chain'} was attempted to be removed.
unit-postgresql-aws-0: 03:18:45 ERROR unit.postgresql-aws/0.juju-log certificates:6: Can't update secret for relation 4
unit-postgresql-aws-0: 03:18:45 ERROR unit.postgresql-aws/0.juju-log certificates:6: Non-existing field 'chain' was attempted to be removed from the databag (relation ID: 4)
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Non-existing secret {'cauth'} was attempted to be removed.
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Can't update secret for relation 4
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Non-existing field 'cauth' was attempted to be removed from the databag (relation ID: 4)
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Non-existing secret {'cert'} was attempted to be removed.
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Can't update secret for relation 4
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Non-existing field 'cert' was attempted to be removed from the databag (relation ID: 4)
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Non-existing secret {'chain'} was attempted to be removed.
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Can't update secret for relation 4
unit-postgresql-aws-1: 03:29:59 ERROR unit.postgresql-aws/1.juju-log certificates:6: Non-existing field 'chain' was attempted to be removed from the databag (relation ID: 4)
unit-tls-certificates-operator-0: 03:30:17 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6cc55752-1e35-4311-85da-b47ad847f61f:r#6#postgresql-aws": settings 6cc55752-1e35-4311-85da-b47ad847f61f:r#6#postgresql-aws not found (not found)
unit-postgresql-aws-1: 03:30:18 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6cc55752-1e35-4311-85da-b47ad847f61f:r#6#tls-certificates-operator": settings 6cc55752-1e35-4311-85da-b47ad847f61f:r#6#tls-certificates-operator not found (not found)
unit-postgresql-aws-1: 03:30:23 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6cc55752-1e35-4311-85da-b47ad847f61f:r#2#postgresql-aws": settings 6cc55752-1e35-4311-85da-b47ad847f61f:r#2#postgresql-aws not found (not found)
machine-5: 03:31:51 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 03:31:51 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-5: 03:31:51 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-gcp-1: 03:31:51 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 03:32:20 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 03:32:20 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-4: 03:32:20 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-gcp-0: 03:32:21 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Non-existing secret {'cauth'} was attempted to be removed.
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Can't update secret for relation 8
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Non-existing field 'cauth' was attempted to be removed from the databag (relation ID: 8)
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Non-existing secret {'cert'} was attempted to be removed.
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Can't update secret for relation 8
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Non-existing field 'cert' was attempted to be removed from the databag (relation ID: 8)
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Non-existing secret {'chain'} was attempted to be removed.
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Can't update secret for relation 8
unit-postgresql-gcp-0: 03:50:55 ERROR unit.postgresql-gcp/0.juju-log certificates:11: Non-existing field 'chain' was attempted to be removed from the databag (relation ID: 8)
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Non-existing secret {'cauth'} was attempted to be removed.
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Can't update secret for relation 8
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Non-existing field 'cauth' was attempted to be removed from the databag (relation ID: 8)
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Non-existing secret {'cert'} was attempted to be removed.
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Can't update secret for relation 8
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Non-existing field 'cert' was attempted to be removed from the databag (relation ID: 8)
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Non-existing secret {'chain'} was attempted to be removed.
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Can't update secret for relation 8
unit-postgresql-gcp-1: 03:59:16 ERROR unit.postgresql-gcp/1.juju-log certificates:11: Non-existing field 'chain' was attempted to be removed from the databag (relation ID: 8)
machine-7: 04:01:22 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-7: 04:01:22 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-7: 04:01:22 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-new-postgresql-0: 04:01:22 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-6: 04:01:55 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-6: 04:01:55 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-6: 04:01:55 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-gcp-2: 04:01:55 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-s3-integrator-0: 04:08:56 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6cc55752-1e35-4311-85da-b47ad847f61f:r#18#postgresql-gcp": settings 6cc55752-1e35-4311-85da-b47ad847f61f:r#18#postgresql-gcp not found (not found)
unit-postgresql-gcp-2: 04:08:57 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: relation scope id "6cc55752-1e35-4311-85da-b47ad847f61f:r#18#s3-integrator": settings 6cc55752-1e35-4311-85da-b47ad847f61f:r#18#s3-integrator not found (not found)
unit-new-postgresql-0: 04:17:25 ERROR unit.new-postgresql/0.juju-log s3-parameters:19: Failed to create a session 'bucket' in region=region.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/src/backups.py", line 217, in _create_bucket_if_not_exists
    s3 = session.resource("s3", endpoint_url=self._construct_endpoint(s3_parameters))
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/session.py", line 446, in resource
    client = self.client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 508, in _get_client_args
    return args_creator.get_client_args(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/args.py", line 137, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: endpoint
unit-new-postgresql-0: 04:17:26 ERROR unit.new-postgresql/0.juju-log s3-parameters:19: Failed to create a session 'bucket' in region=region.
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/src/backups.py", line 217, in _create_bucket_if_not_exists
    s3 = session.resource("s3", endpoint_url=self._construct_endpoint(s3_parameters))
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/session.py", line 446, in resource
    client = self.client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/client.py", line 508, in _get_client_args
    return args_creator.get_client_args(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/args.py", line 137, in get_client_args
    endpoint = endpoint_creator.create_endpoint(
  File "/var/lib/juju/agents/unit-new-postgresql-0/charm/venv/botocore/endpoint.py", line 402, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: endpoint

[32mINFO    [0m pytest_operator.plugin:plugin.py:856 Forgetting main...