[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:486 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:491 Cutting network for postgresql/0
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:497 checking for no connectivity between postgresql/0 and postgresql/2
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:497 checking for no connectivity between postgresql/0 and postgresql/3
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:504 checking for no connectivity between postgresql/0 and the controller
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:511 checking whether the connectivity to the database is not working
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:517 checking whether writes are increasing
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:520 checking whether a new primary was elected
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:527 Restoring network for postgresql/0
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:531 waiting for cluster to become idle
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  postgresql/0 [idle] active: Primary
  postgresql/2 [executing] active: Primary
  postgresql/3 [idle] active: 
[32mINFO    [0m juju.model:model.py:2958 Waiting for model:
  postgresql/0 [idle] active: 
  postgresql/2 [idle] active: Primary
  postgresql/3 [executing] active: 
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:536 waiting for the database service to be ready on postgresql/0
[32mINFO    [0m integration.ha_tests.test_self_healing:test_self_healing.py:540 checking whether the connectivity to the database is working
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:196 checking that the former primary is now a replica
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:202 checking that all units are part of the same cluster
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:216 checking that no writes to the database were missed after stopping the writes
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:220 checking that the former primary is up to date with the cluster after restarting
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model  Controller           Cloud/Region         Version  SLA          Timestamp
test   localhost-localhost  localhost/localhost  3.1.8    unsupported  02:55:36Z

App                  Version  Status  Scale  Charm                Channel  Rev  Exposed  Message
postgresql           14.11    active      3  postgresql                      0  no       
postgresql-test-app           active      1  postgresql-test-app  edge     121  no       received database credentials of the first database

Unit                    Workload  Agent  Machine  Public address  Ports     Message
postgresql-test-app/0*  active    idle   3        10.38.133.136             received database credentials of the first database
postgresql/0            active    idle   0        10.38.133.62    5432/tcp  
postgresql/2*           active    idle   2        10.38.133.223   5432/tcp  Primary
postgresql/3            active    idle   4        10.38.133.34    5432/tcp  

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.38.133.62   juju-89482a-0  ubuntu@22.04      Running
2        started  10.38.133.223  juju-89482a-2  ubuntu@22.04      Running
3        started  10.38.133.136  juju-89482a-3  ubuntu@22.04      Running
4        started  10.38.133.34   juju-89482a-4  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:32:22 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-0: 01:32:22 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:32:22 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-0: 01:32:22 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-2: 01:32:25 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-2: 01:32:25 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:32:25 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-2: 01:32:25 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:32:29 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:32:29 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-3: 01:32:29 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-test-app-0: 01:32:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:32:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:32:30 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
machine-1: 01:32:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-postgresql-1: 01:32:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-4: 01:52:19 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:52:19 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-4: 01:52:19 ERROR juju.worker.dependency "broker-tracker" manifold worker returned unexpected error: no container types determined
unit-postgresql-3: 01:52:19 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-postgresql-0: 01:58:08 ERROR unit.postgresql/0.juju-log Failed to list PostgreSQL database users: connection to server at "10.38.133.34", port 5432 failed: timeout expired

unit-postgresql-0: 01:58:17 ERROR unit.postgresql/0.juju-log Failed to list PostgreSQL database users: connection to server at "10.38.133.34", port 5432 failed: timeout expired

unit-postgresql-test-app-0: 02:40:04 ERROR unit.postgresql-test-app/0.juju-log Unable to drop table
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-test-app-0/charm/./src/charm.py", line 284, in _on_clear_continuous_writes_action
    cursor.execute("DROP TABLE IF EXISTS continuous_writes;")
psycopg2.errors.ReadOnlySqlTransaction: cannot execute DROP TABLE in a read-only transaction

unit-postgresql-0: 02:45:38 ERROR unit.postgresql/0.juju-log Failed to list PostgreSQL database users: connection to server at "10.38.133.34", port 5432 failed: timeout expired

unit-postgresql-0: 02:45:49 ERROR unit.postgresql/0.juju-log Failed to list PostgreSQL database users: connection to server at "10.38.133.34", port 5432 failed: timeout expired

machine-4: 02:46:49 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
machine-0: 02:52:52 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: api connection broken unexpectedly
machine-0: 02:52:52 ERROR juju.worker.uniter.metrics failed to close the collect-metrics listener: close unix /var/lib/juju/agents/unit-postgresql-0/3208488334/s: use of closed network connection
machine-0: 02:52:58 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: i/o timeout
machine-0: 02:53:04 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: i/o timeout
machine-0: 02:53:11 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: i/o timeout
machine-0: 02:53:19 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: i/o timeout
machine-0: 02:53:27 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: connect: no route to host
machine-0: 02:53:37 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: i/o timeout
machine-0: 02:53:48 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: i/o timeout
machine-0: 02:54:00 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: connect: no route to host
machine-0: 02:54:17 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: [908d17] "machine-0" cannot open api: unable to connect to API: dial tcp 10.38.133.53:17070: i/o timeout

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...